kind: pipeline
name: default

steps:
- name: unit test server
  image: rust:1.45
  commands:
    - cd server
    - cargo test

- name: lint client
  image: node:14
  commands:
    - npm i --unsafe-perm
    - npm run compile                                                    
    - npm run lint