pipeline:
  lint:
    image: node:${NODE_VERSION}
    commands:
      - npm i
      - npm run lint
  test:
    image: node:${NODE_VERSION}
    commands:
      - export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sleep 3
      - npm i
      - npm run test

matrix:
  NODE_VERSION:
    - "10-alpine"
    - "9-alpine"
    - "8.11-alpine"
    - "alpine"