kind: pipeline
name: default

steps:
- name: test server
  image: rust:1.43
  commands:
    - cd server
    - cargo test

- name: lint
  image: node:14
  commands:
    - npm i
    - npm run compile                                                    
    - npm run lint