pipeline:
  lint:
    image: node:${NODE_VERSION}
    commands:
      - npm i
      - npm run lint
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm i
      - npm i -g vscode
      - npm run test

matrix:
  NODE_VERSION:
    - "10-alpine"
    - "9-alpine"
    - "8.11-alpine"
    - "alpine"
