---
kind: pipeline
name: Linux

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: rust:1.49-slim-buster
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

---
kind: pipeline
name: Windows

platform:
  os: windows
  arch: amd64

steps:
- name: test
  image: rust:1.49-slim-buster
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

...
