[package]
name = "vscode-mc-shader"
version = "0.1.0"
authors = ["Noah Santschi-Cooney <noah@santschi-cooney.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_lsp = { git = "https://github.com/Strum355/RustLSP" }
serde_json = "1.0.48"
serde = "1.0.104"
walkdir = "2.3.1"
petgraph = "0.5.0"
lazy_static = "1.4.0"
regex = "1.3.4"