name: Test Server
on:
  push:
    branches: [ rust-rewrite ]
  pull_request:
    branches: [ rust-rewrite ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: server
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest, macos-10.15 ]
    steps:
    - uses: actions/checkout@v2
    - name: Build server
      run: cargo build
    - name: Run tests
      run: cargo test
